'use client'
import { useMemo, useState } from 'react'
import { Search } from 'lucide-react'
import { wishes, type WishCategory } from '@/lib/wishes'
import { PageFrame, WishGrid } from '@/components/wishflow-ui'

const categories: (WishCategory | 'All')[] = ['All', 'Education', 'Creator', 'Community', 'Family', 'Health', 'Experience', 'Build', 'Wild']
const sorts = ['Trending', 'New', 'Most supported', 'Almost fulfilled', 'Verified']

export default function DiscoverPage() { const [category, setCategory] = useState<WishCategory | 'All'>('All'); const [sort, setSort] = useState('Trending'); const [query, setQuery] = useState(''); const filtered = useMemo(() => { let result = wishes.filter((wish) => (category === 'All' || wish.category === category) && `${wish.title} ${wish.excerpt} ${wish.location}`.toLowerCase().includes(query.toLowerCase())); if (sort === 'New') result = [...result].sort((a,b) => b.createdAt.localeCompare(a.createdAt)); if (sort === 'Most supported') result = [...result].sort((a,b) => b.supporters - a.supporters); if (sort === 'Almost fulfilled') result = [...result].sort((a,b) => b.raised / b.goal - a.raised / a.goal); if (sort === 'Verified') result = result.filter((wish) => wish.verified); return result }, [category, query, sort]); return <PageFrame title="Discover wishes" description="Find a meaningful idea, meet the person behind it, and help move it forward."><div className="container discover-controls"><label className="search-field"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search wishes, places, or people" aria-label="Search wishes" /></label><div className="category-row" aria-label="Wish categories">{categories.map((item) => <button key={item} className={category === item ? 'filter-chip selected' : 'filter-chip'} onClick={() => setCategory(item)}>{item}</button>)}</div><div className="sort-row"><span>Sort by</span>{sorts.map((item) => <button key={item} className={sort === item ? 'sort-button selected' : 'sort-button'} onClick={() => setSort(item)}>{item}</button>)}</div></div><div className="container discover-results">{filtered.length ? <WishGrid items={filtered} /> : <div className="empty-state"><span className="eyebrow">No wishes found</span><h2>Try a different search.</h2><p>There is always another possibility to discover.</p></div>}</div></PageFrame> }
