'use client'

import { useState } from 'react'
import { ArrowRight, ChevronDown, Compass, Heart, ShieldCheck, Sparkles, Users } from 'lucide-react'

const logoUrl = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WISHFLOW-wMCoEvcI5m7PCmLeeifaNRlr4iaTEY.jpg'

export function ProductHeader({ active = '' }: { active?: string }) {
  return <header className="product-header"><div className="container product-header-inner"><a className="brand-lockup" href="/"><span className="brand-mark"><img src={logoUrl} alt="WISHFLOW" /></span><span className="brand-copy"><strong>WISHFLOW</strong><small>Where wishes become reality.</small></span></a><nav className="product-nav" aria-label="Product navigation"><a className={active === 'discover' ? 'active' : ''} href="/discover">Discover</a><a className={active === 'how' ? 'active' : ''} href="/how-it-works">How it works</a><a className={active === 'about' ? 'active' : ''} href="/about">About</a></nav><div className="product-actions"><a className="button-ghost" href="/login">Sign in</a><a className="button-primary" href="/create">Make a wish <ArrowRight size={16} /></a></div></div></header>
}

export function ProductFooter() { return <footer className="product-footer"><div className="container product-footer-grid"><div><span className="eyebrow">WISHFLOW</span><p>Where genuine wishes meet the people who can help make them real.</p></div><div><strong>Explore</strong><a href="/discover">Discover wishes</a><a href="/how-it-works">How it works</a><a href="/about">About WISHFLOW</a></div><div><strong>Trust</strong><a href="/trust-and-safety">Trust & safety</a><a href="/community-guidelines">Community guidelines</a><a href="/faq">FAQ</a></div><div><strong>Legal</strong><a href="/privacy">Privacy</a><a href="/terms">Terms</a><span>© 2026 WISHFLOW</span></div></div></footer> }

export function ProductFrame({ children, active }: { children: React.ReactNode; active?: string }) { return <div className="product-page"><ProductHeader active={active} /><main className="container product-main">{children}</main><ProductFooter /></div> }

export function InfoPage({ kind }: { kind: 'how' | 'about' | 'safety' | 'guidelines' }) { const data = { how: ['How WISHFLOW works', 'A calmer, more human way to move good ideas forward.', 'WISHFLOW makes meaningful wishes discoverable, then gives communities a clear way to show up.'], about: ['Built for possibility', 'The internet can be more than a place to ask. It can be a place to find your people.', 'WISHFLOW is a private-beta community exploring what happens when generosity is transparent, thoughtful, and easy to act on.'], safety: ['Trust is the product', 'A safer community starts with clear expectations and human review.', 'We design for clarity: verified profiles, transparent progress, report tools, and no promise that every wish will be fulfilled.'], guidelines: ['Community guidelines', 'Be useful. Be honest. Be human.', 'Every wish and response should leave the community more trustworthy than it found it.'] }[kind]; return <ProductFrame active={kind === 'how' ? 'how' : undefined}><section className="product-hero"><span className="eyebrow"><Sparkles size={14} /> WISHFLOW</span><h1>{data[0]}</h1><p className="product-lede">{data[1]}</p><p className="product-copy">{data[2]}</p></section><div className="info-grid"><InfoCard icon={<Compass />} title="Make it clear" text="Share the real story behind a wish, what would change, and what kind of support would help." /><InfoCard icon={<Users />} title="Find your people" text="Discover wishes through categories, context, progress, and the people behind them." /><InfoCard icon={<ShieldCheck />} title="Move with care" text="Support is optional, transparent, and always subject to your own judgment." /></div></ProductFrame> }

function InfoCard({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <article className="info-card"><span className="step-icon">{icon}</span><h2>{title}</h2><p>{text}</p></article> }

export function FaqPage() { const faqs = ['What is WISHFLOW?', 'Do I have to pay to join?', 'How do I report a wish?', 'Are wishes guaranteed to be fulfilled?']; const [open, setOpen] = useState(0); return <ProductFrame><section className="product-hero"><span className="eyebrow">Questions, answered</span><h1>Everything you need to know.</h1><p className="product-lede">A transparent community is built on clear expectations.</p></section><div className="faq-list">{faqs.map((question, index) => <article className="faq-item" key={question}><button onClick={() => setOpen(open === index ? -1 : index)}><span>{question}</span><ChevronDown className={open === index ? 'rotate' : ''} /></button>{open === index && <p>{index === 0 ? 'WISHFLOW is a private-beta platform where genuine wishes meet people who want to help make them real.' : 'WISHFLOW is free to join during private beta. Any future support or payment features will be clearly explained before you use them.'}</p>}</article>)}</div></ProductFrame> }

export function AuthPage({ mode }: { mode: 'login' | 'signup' }) { return <ProductFrame><div className="auth-shell"><div className="auth-card"><span className="eyebrow">{mode === 'login' ? 'Welcome back' : 'Join the beta'}</span><h1>{mode === 'login' ? 'Sign in to WISHFLOW.' : 'Create your WISHFLOW account.'}</h1><p>{mode === 'login' ? 'Pick up where you left off.' : 'Share a wish, support a story, and find your people.'}</p><form><label>Email<input type="email" placeholder="you@example.com" /></label><label>Password<input type="password" placeholder="At least 8 characters" /></label><button className="button-primary" type="button">{mode === 'login' ? 'Sign in' : 'Create account'} <ArrowRight size={16} /></button></form><small>Private beta. Supabase Auth is ready to connect this flow.</small></div></div></ProductFrame> }

export function ProfilePage() { return <ProductFrame><section className="profile-hero"><div className="profile-avatar">AM</div><div><span className="eyebrow">Creator profile</span><h1>Alex Morgan</h1><p>Building thoughtful things and making room for possibility.</p></div><button className="button-secondary"><Heart size={16} /> Follow</button></section><div className="profile-stats"><Stat label="Wishes shared" value="3" /><Stat label="Supported" value="12" /><Stat label="Community trust" value="98%" /></div><h2 className="subheading">Alex&apos;s wishes</h2></ProductFrame> }
function Stat({ label, value }: { label: string; value: string }) { return <div><strong>{value}</strong><span>{label}</span></div> }
